### ISSUE TITLE
Problem with latest update

### ISSUE THREAD

**Issue by a-hofstra** [ashleykleynhans/fooocus-docker#4]
the previous version still starts the most recent is giving an error while booting up:

Loaded LoRA [/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/workspace/Fooocus/modules/default_pipeline.py", line 253, in <module>
    refresh_everything(
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/Fooocus/modules/default_pipeline.py", line 246, in refresh_everything
    final_expansion = FooocusExpansion()
  File "/workspace/Fooocus/extras/expansion.py", line 39, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(path_fooocus_expansion)
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/workspace/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /Fooocus/models/prompt_expansion/fooocus_expansion does not appear to have a file named config.json. Checkout 'https://huggingface.co//Fooocus/models/prompt_expansion/fooocus_expansion/None' for available files.

**Comment by ashleykleynhans** [comment]
What are the 2 versions you are comparing?

**Comment by ashleykleynhans** [comment]
This looks wrong:
```
OSError: /Fooocus/models/prompt_expansion/fooocus_expansion does not appear to have a file named config.json. Checkout 'https://huggingface.co//Fooocus/models/prompt_expansion/fooocus_expansion/None' for available files.
```

It should be in `/workspace/Fooocus` not `/Fooocus`.

**Comment by ashleykleynhans** [comment]
Looks like you installed something in the container disk instead of the persistent storage.

**Comment by ashleykleynhans** [comment]
@a-hofstra my apologies, I have found and resolved the issue.
